### ISSUE TITLE
Published version for Scala 2.10.x throws java.lang.NoClassDefFoundError: com/twitter/finagle/server/DefaultServer

### ISSUE THREAD

**Issue by mayhemm** [okapies/finagle-kafka#17]
This is the full stacktrace:

java.lang.NoClassDefFoundError: com/twitter/finagle/server/DefaultServer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at okapies.finagle.Kafka$.<init>(Kafka.scala:76)
	at okapies.finagle.Kafka$.<clinit>(Kafka.scala)

How can this be fixed?

I'm using Scala 2.10.6 and finagle-kafka 0.2.0

**Comment by okapies** [comment]
What version of finagle-core do you use?

**Comment by mayhemm** [comment]
I don't use finagle-core directly. I use these:

"com.twitter"      %% "finagle-redis"         % "6.35.0"
"com.twitter"      %% "finagle-mysql"         % "6.35.0"

I guess, 6.35.0?

**Comment by okapies** [comment]
Hmm. finagle no longer support Scala 2.10 after 6.35. I recommend you to use Scala 2.11 and its corresponding version instead.

https://finagle.github.io/blog/2016/04/20/scala-210-and-java7/
